#**Array Vs Lists**

# **Numpy**



In [ ]:
import numpy as np

# 1.**Arrays and Lists**
```
 1. List
 2. Array
 3. ** (Power)
 4. sqrt()
 5. exp()
 6. log()
```

In [ ]:
List = [1,2,3]

In [ ]:
A = np.array(List)

In [ ]:
A

array([1, 2, 3])

In [ ]:
A + np.array([6])

array([7, 8, 9])

In [ ]:
A + np.array([4,5,12])

array([ 5,  7, 15])

#Both must Have Same number of Values#

In [ ]:
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
A + np.array([4,5,56,8])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

# In Numpy the value gets multipled (*) or Add (+) in the array




In [ ]:
2 + A

array([3, 4, 5])

#Here it get duplicated

In [ ]:
2 * List

[1, 2, 3, 1, 2, 3]

In [ ]:
List + List

[1, 2, 3, 1, 2, 3]

In [ ]:
List2 = []
for e in List:
  List2.append(e+3)

In [ ]:
List2

[4, 5, 6]

# ** is power
# eg: * **3 power of 3, * **2 power of 2



In [ ]:
List2 = []
for e in List:
  List2.append(e**2)

In [ ]:
List2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
A

array([1, 2, 3])

In [ ]:
A ** 4

array([ 1, 16, 81])

# **sqrt() in Numpy**

In [ ]:
Array = np.sqrt(A)

# **log() in Numpy**

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

# **exp() in Numpy**

In [ ]:
np.exp(A)

# tanh() in Numpy

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
List

[1, 2, 3]

In [ ]:
List2 = []
for e in List:
  List2.append(e+3)

In [ ]:
List2

[4, 5, 6]

# **Dot Product**




In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
print(a.dot(b))

0.47798997924759057


In [ ]:
dot = 0
for i in zip(a,b):
  print(i)
for e, f in zip(a,b):
  dot += e * f
print(dot)

(1, 3)
(2, 4)
11


In [ ]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]


11

In [ ]:
(a * b)

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a*b).sum()

11

In [ ]:
np.dot(a,b)

11

In [ ]:
a @ b

11

In [ ]:
mag = np.sqrt((a * a).sum())

In [ ]:
mag

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
A_dot_B = a.dot(b)

In [ ]:
A_mul_B = (np.linalg.norm(a) * np.linalg.norm(b))

In [ ]:
cosangle = A_dot_B / A_mul_B

In [ ]:
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)

In [ ]:
angle

0.17985349979247847

# **Speed Test**

In [ ]:
## speed comparison
from datetime import datetime

a = np.random.randn(100)
print("a:",a)
b = np.random.randn(100)
print("b:",b)
T = 100000

def slow_dot_product(a,b):
  result= 0
  for e, f in zip(a,b):
    result += e * f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a,b)
dt1 = datetime.now() - t0
print("dt1 for loop:", dt1.total_seconds())

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0
print("dt2 for loop:", dt2.total_seconds())

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())


a: [ 0.34731922  1.06265823  0.09299628 -0.83351495  0.75411587 -0.02977199
 -0.34754014  0.42421374 -0.27462607  0.4400606   0.01080226  1.29125929
 -0.01521681 -2.09931589 -0.64039076 -0.46254204  1.31788892 -0.86726308
 -0.86764837 -1.48510163 -0.90052156 -1.56114626  1.2138009  -2.44165255
 -0.0848671   0.31107817  0.41810374 -0.45566975  0.49586483 -0.16915341
  0.95239605 -0.3024813  -1.26675745 -0.06150701  0.5810124   1.02752169
  0.36613203 -0.19736512 -1.28291636 -0.31225522 -1.03831291 -2.70386642
 -0.45192288  0.37018982  1.24576243 -0.48662188  0.9288616  -1.12304087
  0.32227688  1.22067166  0.72002695  0.64364148  0.10022139  0.46453014
 -0.27826793 -0.49649827 -0.69028207  0.40142278  0.44439547 -0.40745602
  0.36802927  0.854134   -0.53173517  0.08539784 -0.68935973  0.65450451
  1.30634125 -1.20155848 -0.57182522  1.83867224 -0.39119469  0.02649884
  0.82831374  1.53754461 -0.03865301 -0.35825055 -0.80424686 -0.68556383
 -1.09251834 -0.32626417  2.36718873 -1.50939031

# **Matrices**

In [ ]:
array = [[1,2,3],
         [3,4,5],
         [6,7,8]]
array

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [ ]:
np_array = np.array([[1,2,3],
         [3,4,5],
         [6,7,8]])
np_array

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np_array[0][0]

1

In [ ]:
# 0 :- row
# 2 :- column
np_array[0,2]

3

In [ ]:
np_array[:,2]
# : :- select all rows
# 2 :- 2nd column

array([3, 5, 8])

In [ ]:
np_array.T

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 8]])

In [ ]:
np.exp(np_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [ ]:
B = np.array([[1,2,3],
              [4,5,6],
              [5,6,3]])

In [ ]:
np_array.dot(B)

array([[24, 30, 24],
       [44, 56, 48],
       [74, 95, 84]])

In [ ]:
round(np.linalg.det(B))

12

In [ ]:
B

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
np.linalg.inv(B)

array([[-1.75      ,  1.        , -0.25      ],
       [ 1.5       , -1.        ,  0.5       ],
       [-0.08333333,  0.33333333, -0.25      ]])

In [ ]:
np.linalg.inv(B).dot(B)

array([[ 1.00000000e+00, -6.66133815e-16, -7.77156117e-16],
       [ 3.33066907e-16,  1.00000000e+00,  5.55111512e-16],
       [-1.66533454e-16,  1.11022302e-16,  1.00000000e+00]])

In [ ]:
np.trace(B)

9

# **Matrix**

In [ ]:
np.diag([[1,6,8],[2,3,4]])

array([1, 3])

#**Vector**

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(np_array)

EigResult(eigenvalues=array([ 1.40663730e+01, -1.06637298e+00,  3.43927949e-17]), eigenvectors=array([[ 0.26564776,  0.74442863,  0.40824829],
       [ 0.49120712,  0.19070122, -0.81649658],
       [ 0.82954616, -0.63988988,  0.40824829]]))

In [ ]:
evalues , vectors = np.linalg.eig(np_array)

In [ ]:
evalues

array([ 1.40663730e+01, -1.06637298e+00,  3.43927949e-17])

In [ ]:
vectors

array([[ 0.26564776,  0.74442863,  0.40824829],
       [ 0.49120712,  0.19070122, -0.81649658],
       [ 0.82954616, -0.63988988,  0.40824829]])

In [ ]:
vectors[:,0] * evalues[0] ,np_array @ vectors[:,0]

(array([ 3.73670048,  6.90950257, 11.66870569]),
 array([ 3.73670048,  6.90950257, 11.66870569]))

In [ ]:
np.allclose(vectors[:,0] * evalues[0] ,np_array @ vectors[:,0])

True

In [ ]:
np.allclose(vectors @ np.diag(evalues) ,np_array @ vectors)

True

In [ ]:
np.linalg.eigh(np_array)

EighResult(eigenvalues=array([-2.7361167 , -0.42956121, 16.16567792]), eigenvectors=array([[-0.73135516,  0.55193685, -0.40060621],
       [-0.30708641, -0.7909952 , -0.52917345],
       [ 0.60894791,  0.26399301, -0.74799073]]))

# **Solving Linear Systems**

In [ ]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

In [ ]:
np.linalg.solve(A,b)

array([1500.,  700.])

In [ ]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

# **Generating Data**

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
35 * np.ones([2,3])

array([[35., 35., 35.],
       [35., 35., 35.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.9335576666333204

In [ ]:
for _ in np.random.random([4,5]):
  print(_)

[0.084682   0.60527764 0.62389103 0.67353692 0.51741401]
[0.64734533 0.23616957 0.16020206 0.61015676 0.93454073]
[0.79693225 0.42911308 0.56457827 0.90696701 0.55869825]
[0.02219817 0.12302115 0.69915048 0.03983716 0.18195393]


In [ ]:
np.random.randn(4,5)

array([[ 1.31407981, -2.97858817,  0.82673189, -0.99139159, -1.70096656],
       [-0.68088858, -3.30968501, -1.55489592,  0.46219886, -0.06068457],
       [-0.36179988,  0.510105  ,  0.5779752 , -0.2933476 , -0.27585375],
       [ 2.45742578,  0.25413563,  0.62715382,  0.48721965, -1.03796449]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R

array([ 0.31449533, -0.12455174,  0.79141987, ...,  0.32753289,
       -0.96520245, -0.77796278])

In [ ]:
R.mean()

0.006189578452429639

In [ ]:
np.mean(R)

0.006189578452429639

In [ ]:
R.var()

1.0049529161090145

In [ ]:
R.std()

1.0024733992026993

In [ ]:
R = np.random.randn(10000,3)
R

array([[ 1.2055285 ,  1.2631363 , -0.61939655],
       [ 0.85443851,  0.72688303, -0.82275296],
       [ 0.56927985, -1.25373572,  0.56684814],
       ...,
       [ 1.09762016, -1.32604874, -1.46809932],
       [-0.88120438,  0.23701523, -0.04068275],
       [-1.75117953, -0.16653826,  1.58587652]])

In [ ]:
R.mean(axis=0)

array([ 0.0158965 , -0.00865899,  0.01020927])

In [ ]:
R.mean(axis=1).shape

(10000,)

In [ ]:
np.cov(R)

array([[ 1.14626668,  0.99510687, -0.58798186, ...,  0.80167308,
        -0.15778254, -1.54959465],
       [ 0.99510687,  0.87176888, -0.43077136, ...,  0.80541363,
        -0.18700333, -1.41910277],
       [-0.58798186, -0.43077136,  1.10631954, ...,  0.69433504,
        -0.42435802,  0.04891293],
       ...,
       [ 0.80167308,  0.80541363,  0.69433504, ...,  2.07954429,
        -0.80454828, -2.10858784],
       [-0.15778254, -0.18700333, -0.42435802, ..., -0.80454828,
         0.33900131,  0.68170045],
       [-1.54959465, -1.41910277,  0.04891293, ..., -2.10858784,
         0.68170045,  2.78633143]])

In [ ]:
np.cov(R.T)

array([[ 0.99785215, -0.00756078,  0.00222689],
       [-0.00756078,  0.99119463, -0.00949133],
       [ 0.00222689, -0.00949133,  0.98791029]])

In [ ]:
np.cov(R,rowvar=False)

array([[ 0.99785215, -0.00756078,  0.00222689],
       [-0.00756078,  0.99119463, -0.00949133],
       [ 0.00222689, -0.00949133,  0.98791029]])

In [ ]:
np.random.randint(0,15,size=(4,4))

array([[ 4, 12, 14,  2],
       [ 2, 11,  3,  2],
       [ 2,  6,  1,  8],
       [13,  0, 10,  4]])

In [ ]:
np.random.choice(10,size=[3,5])

array([[7, 2, 7, 6, 3],
       [6, 3, 3, 0, 1],
       [9, 5, 1, 1, 1]])

# **Dot Product**

In [ ]:
A = np.random.choice(10,size=[3,3])
B = np.random.choice(10,size=[3,3])

In [ ]:
A = np.array([[1, 2], [2, 3], [4, 5]])
B = np.array([[4, 5, 1], [6, 7, 2]])

In [ ]:
C = A.dot(B)

In [ ]:
C

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

# **CROSS PRODUCT**


```
# Its can happen only with same size matrices
# In cross no np.array() needed
# Eg: Cross_A = [[1, 2], [2, 3]]
```
# **DOT PRODUCT**


```
# Both Sizes are ok
# np.array() is necessary
#Eg:A = np.array([[1, 2], [2, 3], [4, 5]])

```




In [ ]:
Cross_A = [[1, 2], [2, 3]]
Cross_B = [[4, 5, 1], [6, 7, 2]]

In [ ]:
np.cross(Cross_A,Cross_B)

array([[ 2, -1, -3],
       [ 6, -4, -4]])

# **Also '@' is used for dot product**

In [ ]:
A @ B

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])